# Exercício:

## 1 – Um objeto composto multidimensional (matriz) pode receber  objeto composto unidimensional (vetor)?

Sim, pois uma matriz abrange a inclusão de objetos compostos em um objeto.

## 2 – No exercício 9 da última aula, foram instanciadas 5 listas. Instancie um objeto composto multidimensional da classe lista com estes cinco vetores. Recupere a matriz.

In [5]:
# Vetores criados na questão 9
srs12b = [6, 'sr', 0, False]
sag1 = [4, 'sa', 1, False]
gra1 = [4, 'gr', 1, False]
tuba1 = [5, 'tu', 1, False]
sag3 = [4, 'sa', 1, False]

In [6]:
lista_2 = [
    srs12b,
    sag1,
    gra1,
    tuba1,
    sag3
]
print(lista_2)

[[6, 'sr', 0, False], [4, 'sa', 1, False], [4, 'gr', 1, False], [5, 'tu', 1, False], [4, 'sa', 1, False]]

## 3 – Copie e converta o objeto instanciado no exercício 2 para um NumPy array. Recupere o array.

In [7]:
import numpy as np

In [8]:
array = np.array(lista_2)
print(array)

[['6' 'sr' '0' 'False']
 ['4' 'sa' '1' 'False']
 ['4' 'gr' '1' 'False']
 ['5' 'tu' '1' 'False']
 ['4' 'sa' '1' 'False']]

## 4 – Recupere todos os itens do terceiro gene.

In [9]:
print(array[2,])

['4' 'gr' '1' 'False']

## 5 – Verifique se todos os nomes dos genes tem ou não os caracteres 'hu'.

In [10]:
genes_toxoplasma = ["srs12b", "sag1", "gra1", "tuba1", "sag3"]

In [11]:
questao_5 = [
    "hu" in genes_toxoplasma[0],
    "hu" in genes_toxoplasma[1],
    "hu" in genes_toxoplasma[2],
    "hu" in genes_toxoplasma[3],
    "hu" in genes_toxoplasma[4]
]
print(questao_5)

[False, False, False, False, False]

## 6 – Recupere do segundo e quarto genes, os dois primeiros caracteres dos nomes e os quantitativos de 'a' presentes nos nomes dos genes.

In [12]:
print(
    [genes_toxoplasma[1][:2], genes_toxoplasma[1].count("a")],
    [genes_toxoplasma[3][:2], genes_toxoplasma[3].count("a")]
    )

['sa', 1] ['tu', 1]

## 7 – Converta o objeto instanciado no exercício 10 da aula anterior para uma DataFrame Pandas. Nesta DataFrame, os index devem ser os nomes dos genes e cada coluna deve ter um nome que indique seu conteúdo. Recupere a DataFrame.

In [13]:
import pandas as pd

In [14]:
# Objeto da questão 10
questao10 = {
    "srs12b": srs12b,
    "sag1": sag1,
    "gra1": gra1,
    "tuba1": tuba1,
    "sag3": sag3
}
print(questao10)

{'srs12b': [6, 'sr', 0, False], 'sag1': [4, 'sa', 1, False], 'gra1': [4, 'gr', 1, False], 'tuba1': [5, 'tu', 1, False], 'sag3': [4, 'sa', 1, False]}

In [15]:
df = pd.DataFrame(questao10)
df.index = ["numero de caracteres", "2 primeiros caracteres", "quantos 'a' existem", "presença de 'hu'"]
df = df.transpose()
df

,numero de caracteres,2 primeiros caracteres,quantos 'a' existem,presença de 'hu'
srs12b,6,sr,0,False
sag1,4,sa,1,False
gra1,4,gr,1,False
tuba1,5,tu,1,False
sag3,4,sa,1,False

In [16]:
df.to_csv('genes0607.csv')

## 8 – Da DataFrame do exercício anterior recupere os números de caracteres e quantas vezes aparece o caractere ‘a’ de todos os genes.

In [17]:
df[["numero de caracteres", "quantos 'a' existem"]]

       numero de caracteres quantos 'a' existem
srs12b                    6                   0
sag1                      4                   1
gra1                      4                   1
tuba1                     5                   1
sag3                      4                   1

## 9 – Da DataFrame do exercício anterior recupere se no nome aparecem os caracteres ‘hu’, para o primeiro e o terceiro genes.

In [18]:
df.iloc[[0, 2], 3]

srs12b    False
gra1      False
Name: presença de 'hu', dtype: object

In [19]:
df.iloc[[0, 2], 3][df.iloc[[0, 2], 3] == True]

Series([], Name: presença de 'hu', dtype: object)

## 10 – Importe o data.csv (dados de seguro na Flórida em 2012) para uma DataFrame. Armazene em um dicionário o número de entradas, uma lista com as classes das colunas e outra lista com o número de elementos de cada classe, três listas, contendo a média, o desvio padrão e o terceiro quartil da primeira, quarta e nona colunas . Recupere o dicionário.

In [20]:
import os
import pandas as pd

In [21]:
df = pd.read_csv('data.csv')
df

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [22]:
numero_entradas = df.shape
numero_entradas

(36634, 18)

In [23]:
classe_colunas = df.dtypes
classe_colunas

policyID                int64
statecode              object
county                 object
eq_site_limit         float64
hu_site_limit         float64
fl_site_limit         float64
fr_site_limit         float64
tiv_2011              float64
tiv_2012              float64
eq_site_deductible    float64
hu_site_deductible    float64
fl_site_deductible    float64
fr_site_deductible      int64
point_latitude        float64
point_longitude       float64
line                   object
construction           object
point_granularity       int64
dtype: object

In [24]:
elementos_classe = list(df.dtypes.value_counts())
elementos_classe

[11, 4, 3]

In [25]:
colunas139 = df.iloc [: , [0,3,8]]
colunas139

       policyID  eq_site_limit    tiv_2012
0        119736       498960.0   792148.90
1        448094      1322376.3  1438163.57
2        206893       190724.4   192476.78
3        333743            0.0    86854.48
4        172534            0.0   246144.49
...         ...            ...         ...
36629    404309            0.0   155065.65
36630    465875      1297057.5  1577500.79
36631    791209       173286.9   205527.97
36632    322627      1499781.6  1768782.43
36633    398149       373488.3   596003.67

[36634 rows x 3 columns]

In [26]:
media = colunas139.mean()
media

policyID         5.486619e+05
eq_site_limit    7.314780e+05
tiv_2012         2.571004e+06
dtype: float64

In [27]:
desvio_padrao = colunas139.std()
desvio_padrao

policyID         2.599129e+05
eq_site_limit    1.752300e+07
tiv_2012         2.036777e+07
dtype: float64

In [28]:
quartil = colunas139.quantile(0.75)
quartil

policyID         7.742520e+05
eq_site_limit    0.000000e+00
tiv_2012         1.128871e+06
Name: 0.75, dtype: float64

In [29]:
dicionario10 = {
    "numero de entradas": numero_entradas,
    "classe das colunas": classe_colunas,
    "numero de elementos": elementos_classe,
    "media": media,
    "desvio padrao": desvio_padrao,
    "terceiro quartil": quartil
}
dicionario10

{'numero de entradas': (36634, 18),
 'classe das colunas': policyID                int64
 statecode              object
 county                 object
 eq_site_limit         float64
 hu_site_limit         float64
 fl_site_limit         float64
 fr_site_limit         float64
 tiv_2011              float64
 tiv_2012              float64
 eq_site_deductible    float64
 hu_site_deductible    float64
 fl_site_deductible    float64
 fr_site_deductible      int64
 point_latitude        float64
 point_longitude       float64
 line                   object
 construction           object
 point_granularity       int64
 dtype: object,
 'numero de elementos': [11, 4, 3],
 'media': policyID         5.486619e+05
 eq_site_limit    7.314780e+05
 tiv_2012         2.571004e+06
 dtype: float64,
 'desvio padrao': policyID         2.599129e+05
 eq_site_limit    1.752300e+07
 tiv_2012         2.036777e+07
 dtype: float64,
 'terceiro quartil': policyID         7.742520e+05
 eq_site_limit    0.000000e+00
 tiv_2012         1.128871e+06
 Name: 0.75, dtype: float64}